<a href="https://colab.research.google.com/github/JoacoPagani/Data-Science-II-Machine-Learning-para-la-Ciencia-de-Datos/blob/main/ejercicios_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<a href="https://colab.research.google.com/github/NicolasCaminos/Python/blob/v0.1/Data_Science_Tutorials/ejercicios_api.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ejercicio 1: Consultar una API y Analizar Datos con Pandas


Utiliza la API de JSONPlaceholder (https://jsonplaceholder.typicode.com/) para obtener datos de usuarios (/users) y publicaciones (/posts).

Almacena los datos obtenidos en estructuras de datos de Pandas (por ejemplo, DataFrames).

Combina la información de usuarios y publicaciones en un solo DataFrame utilizando la clave externa (userId).

Realiza algunas operaciones básicas de exploración y análisis de datos con Pandas, como contar el número de publicaciones por usuario, encontrar el usuario con más publicaciones, etc.

In [ ]:
#Consulta a Api + Merge entre 2 Df

import requests
import pandas as pd
import json

urlPosts = 'https://jsonplaceholder.typicode.com/posts'
urlUsers = 'https://jsonplaceholder.typicode.com/users'


responsePosts = requests.get(urlPosts)
responseUsers = requests.get(urlUsers)

dataPosts = responsePosts.json()
dataUsers = responseUsers.json()

dfPosts = pd.DataFrame(dataPosts)
dfUsers = pd.DataFrame(dataUsers)

dfMerge = pd.merge(dfPosts, dfUsers, left_on='userId', right_on='id', suffixes=('_post', '_user'))
dfMerge.head()

,userId,id_post,title,body,id_user,name,username,email,address,phone,website,company
0,1,1,sunt aut facere repellat provident occaecati e...,quia et suscipit\nsuscipit recusandae consequu...,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
1,1,2,qui est esse,est rerum tempore vitae\nsequi sint nihil repr...,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
2,1,3,ea molestias quasi exercitationem repellat qui...,et iusto sed quo iure\nvoluptatem occaecati om...,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
3,1,4,eum et est occaecati,ullam et saepe reiciendis voluptatem adipisci\...,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."
4,1,5,nesciunt quas odio,repudiandae veniam quaerat sunt sed\nalias aut...,1,Leanne Graham,Bret,Sincere@april.biz,"{'street': 'Kulas Light', 'suite': 'Apt. 556',...",1-770-736-8031 x56442,hildegard.org,"{'name': 'Romaguera-Crona', 'catchPhrase': 'Mu..."

In [ ]:
#Analisis de Datos

post_counts = dfMerge.groupby('name')['id_post'].count()
print("Número de publicaciones por usuario:\n", post_counts)

userMasPosts = post_counts.idxmax()
print("\nUsuario con más publicaciones:", userMasPosts)

Número de publicaciones por usuario:
 name
Chelsey Dietrich            10
Clementina DuBuque          10
Clementine Bauch            10
Ervin Howell                10
Glenna Reichert             10
Kurtis Weissnat             10
Leanne Graham               10
Mrs. Dennis Schulist        10
Nicholas Runolfsdottir V    10
Patricia Lebsack            10
Name: id_post, dtype: int64

Usuario con más publicaciones: Chelsey Dietrich

## Ejercicio 2: Consumir una API de Datos Financieros


Utiliza la API de Alpha Vantage (https://www.alphavantage.co/) para obtener datos históricos de precios de una acción específica.

Almacena los datos en un DataFrame de Pandas.

Calcula la media móvil de los precios de cierre para generar una señal de compra/venta.

Visualiza los precios de cierre y la media móvil en un gráfico.

In [ ]:
urlStock = 'https://www.alphavantage.co/query?function=TIME_SERIES_DAILY&symbol=MELI&apikey=6OYZ9C1GTV3J0ZPV'

responseStock = requests.get(urlStock)

textStock = responseStock.text

jsonData = json.loads(textStock)
dfStock = pd.DataFrame(jsonData)
dfStock

,Meta Data,Time Series (Daily)
1. Information,"Daily Prices (open, high, low, close) and Volumes",NaN
2. Symbol,MELI,NaN
3. Last Refreshed,2024-08-02,NaN
4. Output Size,Compact,NaN
5. Time Zone,US/Eastern,NaN
...,...,...
2024-03-18,NaN,"{'1. open': '1524.8100', '2. high': '1529.6050..."
2024-03-15,NaN,"{'1. open': '1560.2100', '2. high': '1567.5000..."
2024-03-14,NaN,"{'1. open': '1555.6600', '2. high': '1583.4900..."
2024-03-13,NaN,"{'1. open': '1546.0000', '2. high': '1558.7600..."
2024-03-12,NaN,"{'1. open': '1553.1100', '2. high': '1575.0000..."

## Ejercicio 3: API de Clima


Utiliza la API de OpenWeatherMap (https://openweathermap.org/api) para obtener datos climáticos.

Solicita datos climáticos para una ciudad específica.

Almacena la información relevante en un DataFrame de Pandas.

Realiza un análisis exploratorio simple, como calcular la temperatura promedio o visualizar la evolución de la temperatura a lo largo del tiempo.

## Ejercicio 4: API de Películas y Análisis con Pandas

Utiliza la API de The Movie Database (TMDb) (https://www.themoviedb.org/documentation/api) para obtener información sobre películas.

Consulta datos sobre películas populares o de un género específico.

Almacena los datos en un DataFrame de Pandas.

Realiza un análisis exploratorio, como encontrar las películas con la mayor puntuación, la duración promedio, etc.

Aclaraciones:

- JSONPlaceholder API:

JSONPlaceholder (https://jsonplaceholder.typicode.com/) es una API de prueba gratuita diseñada para simular una API RESTful real sin almacenar datos permanentes. Puedes utilizarla libremente para practicar y aprender sobre el manejo de datos en APIs.
-  Alpha Vantage API:

Alpha Vantage (https://www.alphavantage.co/) ofrece una API gratuita con ciertas limitaciones, pero debería ser suficiente para realizar prácticas y ejercicios. Al registrarte en su plataforma, obtendrás una clave de API gratuita que puedes usar para acceder a los datos financieros.
- OpenWeatherMap API:

OpenWeatherMap (https://openweathermap.org/api) proporciona una API con un plan gratuito limitado que incluye acceso a datos climáticos básicos. Necesitarás registrarte para obtener una clave de API gratuita.
- The Movie Database (TMDb) API:

TMDb (https://www.themoviedb.org/documentation/api) ofrece una API gratuita con opciones de acceso a datos sobre películas y programas de televisión. Debes registrarte para obtener una clave de API gratuita.